In [1]:
import numpy as np
import random

Creating numpy arrays

In [59]:
#Creating an array with random integers
arr1=np.random.randint(1,50,4)

In [60]:
arr1

array([47, 26,  1,  3])

In [61]:
#Creating an array with random integers
arr2=np.random.randint(1,50,4)

In [62]:
arr2

array([32, 24, 13, 25])

Basic Operations on arrays

In [63]:
#Return no.of dimensions(axes) of the array
arr1.ndim

1

In [64]:
#Returns the tuple of integers indicating the size of array in each dimension
arr1.shape

(4,)

In [65]:
#Returns the size of the array
arr1.size

4

In [66]:
#Returs the data type of the array
arr1.dtype

dtype('int64')

In [67]:
#Return the size of each element in the array
arr1.itemsize

8

In [68]:
#return the total number of bytes for all elements in the array
arr1.nbytes

32

Data manipulation

In [69]:
#indexing
arr1[2]

1

In [13]:
#Slicing

In [45]:
arr1[1:3]

array([ 7, 41])

In [46]:
arr2[1:5]

array([42, 32, 21, 11])

In [47]:
#Creating a 2d array using replalce
arr2d=np.arange(0,20,2).reshape(2,5)

In [48]:
arr2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [49]:
#indexing a 2d array the : left side represents the rows and right side represents the columns
arr2d[:2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [50]:
arr2d1=np.arange(0,40,4).reshape(2,5)

In [51]:
arr2d1

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36]])

In [52]:
T_arr=arr2d1.T

Mathematical Operations

In [70]:
#Addition
arr1+arr2

array([79, 50, 14, 28])

In [71]:
#Subtraction
arr2-arr1

array([-15,  -2,  12,  22])

In [72]:
#multiplication
arr1*arr2

array([1504,  624,   13,   75])

In [ ]:
#division
arr2/arr1

array([ 1.08823529, 10.72      ,  3.30120482,  2.01162791,  0.88235294,
       87.        ,  2.78571429,  3.86585366,  0.50847458,  5.4       ])

In [73]:
arr2 ** 2

array([1024,  576,  169,  625])

Matrix operation

In [74]:
#Matrix multiplication (Dot Product)
np.dot(arr2d,T_arr)

array([[ 240,  640],
       [ 640, 2040]])

In [75]:
#Matrix Multiplication
arr2d*arr2d1

array([[  0,   8,  32,  72, 128],
       [200, 288, 392, 512, 648]])

In [76]:
#Matrix Additio
arr2d+arr2d1

array([[ 0,  6, 12, 18, 24],
       [30, 36, 42, 48, 54]])

In [77]:
#Matrix Subtraction
arr2d1-arr2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [78]:
#Matrix Division
arr2d1/arr2d

<ipython-input-78-31678e20479f>:2: RuntimeWarning: invalid value encountered in divide
  arr2d1/arr2d


array([[nan,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  2.,  2.]])

Numpy Aggregation Functions

In [84]:
#Sum function in numpy arrays
print("Sum of all elements in the array")
print(np.sum(arr1))
#Sum along the axis
print("Sum along the 0th axis")
print(np.sum(arr2d,axis=0))
print("Sum along the 1st axis")
print(np.sum(arr2d,axis=1))

Sum of all elements in the array
77
Sum along the 0th axis
[10 14 18 22 26]
Sum along the 1st axis
[20 70]


In [85]:
#Min value in the array
print("Min value of the array")
print(np.min(arr1))
#Max value of the array
print("Max value of the array")
print(np.max(arr1))


Min value of the array
1
Max value of the array
47


In [86]:
#Mean of the array
print("Mean value of the array")
print(np.mean(arr1))


Mean value of the array
19.25


In [87]:
#Median of the array
print("Median value of the array")
print(np.median(arr1))

Median value of the array
14.5
